### PR TITLE
testing CodeShip

### PR DESCRIPTION
**Pull request by chaudhary27**
On Kevin's suggestion testing CodeShip.

### CODE REVIEW

**Comment by chaudhary27** [comment]
@NehemiahAndrews I am sold on CodeShip. Please input your opinion :+1: :-1:

**Comment by chaudhary27** [comment]
plz do NOT merge this pull request. need to edit CodeShip so it deploys to heroku when pushed to master. right now it deploys to heroku when pushed to this branch only.

**Comment by NehemiahAndrews** [comment]
@chaudhary27 Code ship looks pretty slick.  I'm totally okay with shifting from Travis to Codeship if you   think it will suit our needs better. Go ahead and update Codeship to deploy on master, remove the Travis .yml, and update the README and I'll merge.

**Comment by chaudhary27** [comment]
I think we are all set (travis is switched off and CodeShip is on). please review and merge. thanks.

**Comment by NehemiahAndrews** [comment]
Reviewed code, everything looks good. Merging.

**Pull request merged**
