### PR TITLE
King.valid_move

### PR DESCRIPTION
**Pull request by chaudhary27**
I am trying **King.valid_move** with Single Table Inheritance. Trying to understand and following this article --> http://samurails.com/tutorial/single-table-inheritance-with-rails-4-part-1

**I still do not understand STI**

I def need help :construction_worker:  

@gruzzlymug can you please push me in the right direction. thanks!

### CODE REVIEW

**Comment by gruzzlymug** [comment]
Yes, I can help. I would suggest trying to be specific about asking questions when asking for help. We need to figure out how far your understanding goes, and where it's breaking down. So being specific about your question can help determine that. Otherwise, there is potentially a lot to explain :) Where is your code working? Where is your code breaking?

First thing I would say is that naming stuff meaningfully will facilitate understanding. So take a look at the name of your base class. I would change that. Part of object oriented design is understanding 2 relationships: Is-A and Has-A. See this article for a brief overview:
http://www.w3resource.com/java-tutorial/inheritance-composition-relationship.php

When you're reading the article I posted (referenced in your comment), think of the Tribe as the Game, and the Animal as the Piece.

**Comment by gruzzlymug** [comment]
Also, I made an example Rails STI app in the Cloud 9 workspace. It's named sti.

When I run the rails console, I can create a King like so:
vopijibib@rails_scratch_pad:~/workspace/sti $ rails c
Loading development environment (Rails 4.2.1)
2.2.1 :001 > k = King.new
 => #<King id: nil, name: nil, game_id: nil, user_id: nil, x_pos: nil, y_pos: nil, type: "King", created_at: nil, updated_at: nil> 
2.2.1 :002 > k.save
   (0.3ms)  BEGIN
  SQL (0.5ms)  INSERT INTO "pieces" ("type", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["type", "King"], ["created_at", "2015-09-07 16:46:33.478996"], ["updated_at", "2015-09-07 16:46:33.478996"]]
   (2.9ms)  COMMIT
 => true 
2.2.1 :003 > k.type
 => "King" 

Something like this could be a basis for a test.

**Comment by chaudhary27** [comment]
thanks @gruzzlymug. will def look out for comprehensive questions to ask next time around. meanwhile above explanation shall help me a lot :smile:

**Comment by chaudhary27** [comment]
**UPDATE**
* changed variable name category --> type. updated anywhere it was used. tested code with updated variable name. I had to do it because I couldn't get STI working w/o type column. I spent bunch of time trying to find a way but all in vain had to change it to type.

Question:
* Can someone help me write tests for this. My failing tests are passing. I do not know if I am not writing the test code correctly or if my king.rb logic is wrong. You can look at current tests in piece_test.rb

**Comment by gruzzlymug** [comment]
I merged locally and created a King. That worked. I would recommend adding some tests for the various types to the piece_test.rb file like this:

```
  test "King type" do
    k = FactoryGirl.create(:king)
    assert_equal(k.type, "King")  
  end
```

**Comment by NehemiahAndrews** [comment]
@chaudhary27 - Looks great man! If you can add the rest of the factories and tests like @gruzzlymug mentioned (we should have one for each piece type at this point in time) I'll merge today.

**Comment by chaudhary27** [comment]
@NehemiahAndrews added tests to check :type for rest of the pieces. Thanks for pointing it out :smile:

**Pull request merged**
