### PR TITLE
Added piece model

### PR DESCRIPTION
**Pull request by chaudhary27**
# Piece Model

**Piece table includes**
* t.integer :row_pos
* t.integer :col_pos
* t.belongs_to :user
* t.belongs_to :game
* t.string :type

**Associations**

**piece.rb**    

* belongs_to :user, :foreign_key => 'user_id'
* belongs_to :game, :foreign_key => 'game_id'

**user.rb**
* has_many :pieces

**game.rb**
* has_many :pieces

**Test Piece Model in rails console**
> Piece.create(:user_id => '1', :game_id => '1', :position => [0,1])

### CODE REVIEW

**Comment by gruzzlymug** [comment]
I have a couple comments but I'm going to wait til the rest of the group has a chance to comment.

**Comment by NehemiahAndrews** [comment]
@chaudhary27 - Here are my thoughts.
1. In piece.rb, there's no need to add the :foreign_key assignment, it is implicit in the belongs_to declaration.
2. In your user model, you should eliminate has_many games as that is redundant and may actually conflict with other mapping we have in place.
3. The migration file data types for user_id and game_id should be t.belongs_to instead of t.integer to build up database associations.
4. Last, and this doesn't really impact functionality right now but it's important to be consistent, is that there isn't a Piece defined in your factories.rb.  
5. The game model needs to be updated with has_many pieces

Don't mean to pick things apart, but really I think items 2,3, and 5 are critical to ensure a functional app and 1 and 4 are more workflow/style related.

**Comment by chaudhary27** [comment]
waiting for @gruzzlymug comments/suggestions. will make changes then :goat:

**Comment by chaudhary27** [comment]
thanks @NehemiahAndrews for in-depth review!

**Comment by chaudhary27** [comment]
plz merge on @gruzzlymug green signal :green_heart:

**Comment by gruzzlymug** [comment]
Think about these 2 questions:
1) How are you going to determine what type of piece you are working with?
2) How are you going to use a piece's data to implement the is_obstructed? method?

**Comment by gruzzlymug** [comment]
I don't want to hold you up with merges, you don't have to wait for me. I'd rather see you move forward and experiment and test your ideas than wait for me :) I can always make comments later.

**Comment by gruzzlymug** [comment]
Here's another way to work together. If 2 of you are working and one has work that depends on the other, then the person working on the dependent task could merge the PR on a new branch and start working while the rest of the team reviews.

For example, if Faisal is working on the Piece and Nehemiah is working on is_obstructed?, then Nehemiah could (in theory) merge the PR while it is still under review. Then he would be able to give insightful feedback based on using Faisal's code.

If you coordinate and work concurrently, that works better.

**Comment by gruzzlymug** [comment]
looks good to me

**Pull request merged**
