### PR TITLE
Added hero img, fonts, fixed footer to homepage

### PR DESCRIPTION
**Pull request by vincentchin**
# Static Home Page Changes

* Added high resolution hero image (chess related)
* Added Josefin Slab and Josefin Sans font for headline text and paragraph text for content
* Added a fixed footer with icon links to Github, theFirehoseProject and Facebook (in case we ever need it)

### CODE REVIEW

**Comment by vincentchin** [comment]
Also if anyone knows how to prevent adding .DS_Store files (hidden files on mac) when doing a PR, that'd be great to know.

**Comment by NehemiahAndrews** [comment]
@vincentchin I'm not going to be able to review and merge until 8 or 9 tonight, hopefully someone else can get to it sooner.  

This link explains how to address the .ds_store issue. 
http://stackoverflow.com/questions/18393498/gitignore-all-the-ds-store-files-in-every-folder-and-subfolder

**Comment by NehemiahAndrews** [comment]
@vincentchin  Looks great!  If you can clean up that .ds_store issue and re-commit I'll merge.

**Comment by vincentchin** [comment]
Woops...Ignore that, looks like that didn't work.

**Comment by NehemiahAndrews** [comment]
@vincentchin Merged. Deleting branch.

**Pull request merged**
