### PR TITLE
Draw pieces on board

### PR DESCRIPTION
**Pull request by NehemiahAndrews**
This code triggers board population and represents all pieces on the board with text.

### CODE REVIEW

**Comment by gruzzlymug** [comment]
I have couple comments for you on the selected piece helper method.

First thing is, you might want to consider its return value, just the type of piece. That does not give you any way to determine the color of the piece. You might consider returning a piece object.

Next, think about how you are solving the problem. The solution performs a query for every single square on the board. That's 64 queries. Generally, queries take a long time (in computer time) and so you should strive to minimize the number of times you call the database. If you try to follow that maxim, it might result in a different approach to the algorithm.

In a case like this, it's not going to matter a lot. But in production code, you can't really do this type of thing because it just doesn't scale. For now, I recommend leaving the code as is for the PR. If you have time to address this issue afterwards, then feel free to do so. I can help you with this but I would recommend you spend some time thinking about how to do it first.

Lastly, and this is a bit nit picky, you might consider the name of the selected_piece method. Naming is subtle and there is nothing inherently wrong with the name. But to me, it implies that there is a specific piece already selected and the method is getting that piece. Or alternatively, the name might give you the idea that a piece is being "selected" at that x, y spot. Anyway, the word select implies some stuff that is (IMO) not going on in the method. To me, a name like "find_piece_at position" is more in line with what it's doing.

**Comment by gruzzlymug** [comment]
Here's another somewhat random comment. It has to do with writing IF statements. Take this example:

    def show
        @game = Game.where(:id => params[:id]).first
        if @game.blank?
            render :text => "Not found", :status => :not_found
        else
            @pieces = @game.pieces.to_a
        end
    end

It's a matter of style, and not strictly required, but generally it's a good idea to put the "normal" case as part of the IF block, and the exceptional/non-normal case for the ELSE. The idea is you want to make reading and understanding the code easy. Using a convention like this puts the normal case in a prominent position, and consistent treatment let's people know where to look for certain types of logic.

So I would change the test to "if !@game.blank?"

Also, you might see if changing the code to use empty? instead of blank? because blank? is slower. See this blog:
http://hashrocket.com/blog/posts/rails-quick-tips-easy-activerecord-optimizations

**Comment by gruzzlymug** [comment]
I was just testing out the PR to see if there were any inaccuracies in what I said above. I created 2 users and one game, then joined the game w/ the 2nd user. I got an error on line 34 of games_controller (the line starting with 'else'):

Extracted source (around line #34):
          
        if current_user.id == @game.player_white_id
            redirect_to game_path(@game)
        else player_black_id == nil
            @game.update(:player_black_id => current_user.id)
            @game.populate_board
            redirect_to game_path(@game)

**Comment by NehemiahAndrews** [comment]
Thanks @gruzzlymug  - That's what I get for getting something working, then tinkering... I see the issue and I'll correct and re-push and update tests to catch.

**Comment by NehemiahAndrews** [comment]
@gruzzlymug Lol - I read the last comment and replied.  Appreciate the feedback, will definitely update to correct issues and I'll come up with some ideas for refactors and discussion later. :goat:

**Comment by chaudhary27** [comment]
pulled in and tested locally. looks good. :ship: :shipit:

**Pull request merged**
